# Generated by Django 5.2.10 on 2026-04-06 10:14

import django.db.models.deletion
import event.models.registration.registration
import event.models.registration.ticket
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentProjectSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Event Name",
                    ),
                ),
                (
                    "sheet_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The ID of the Google Sheet containing project and schedule data.",
                        max_length=255,
                        verbose_name="Google Sheet ID",
                    ),
                ),
                (
                    "tracks_gid",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="The GID of the worksheet containing track definitions.",
                        null=True,
                        verbose_name="Tracks Worksheet GID",
                    ),
                ),
                (
                    "projects_gid",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="The GID of the worksheet containing project/slot data.",
                        null=True,
                        verbose_name="Projects Worksheet GID",
                    ),
                ),
                (
                    "show_winners",
                    models.BooleanField(
                        default=False,
                        help_text="Display winner data on the schedule page.",
                        verbose_name="Show Winners",
                    ),
                ),
                (
                    "grand_winners",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Auto-synced from Google Sheet Award rows.",
                        verbose_name="Grand Winners",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("sync_error", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Current Project and Schedule",
                "verbose_name_plural": "Current Project and Schedule",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_live", models.BooleanField(default=False)),
                (
                    "allow_secondary_email",
                    models.BooleanField(
                        default=False,
                        help_text="Prompt registrants to enter a secondary email address.",
                    ),
                ),
                (
                    "collect_phone",
                    models.BooleanField(
                        default=False,
                        help_text="Show a phone number field on the registration form.",
                    ),
                ),
                (
                    "verify_phone",
                    models.BooleanField(
                        default=False,
                        help_text="Require phone number verification via SMS code. Only applies when phone collection is enabled.",
                    ),
                ),
                (
                    "registration_sheet_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The ID of the Google Sheet used to sync event registration data.",
                        max_length=255,
                        verbose_name="Registration Google Sheet ID",
                    ),
                ),
                (
                    "registration_sheet_gid",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="The GID of the worksheet within the registration sheet.",
                        null=True,
                        verbose_name="Registration Worksheet GID",
                    ),
                ),
                (
                    "registration_sheet_synced_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Last Sheet Sync",
                    ),
                ),
                (
                    "registration_sheet_sync_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Last Sync Row Count"
                    ),
                ),
                (
                    "registration_sheet_sync_error",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        verbose_name="Last Sync Error",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        help_text='E.g. "Main Entrance", "VIP Gate", "Morning Session"',
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this check-in point is currently accepting scans.",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_ins",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventScheduleSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("start_time", models.CharField(default="1:00", max_length=10)),
                ("slot_minutes", models.PositiveIntegerField(default=30)),
                (
                    "accent_color",
                    models.CharField(blank=True, default="#002856", max_length=20),
                ),
                (
                    "config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_sections",
                        to="event.currentprojectschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="EventScheduleTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("track_number", models.PositiveIntegerField()),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                ("room", models.CharField(blank=True, default="", max_length=255)),
                ("zoom_link", models.CharField(blank=True, default="", max_length=500)),
                ("topic", models.CharField(blank=True, default="", max_length=255)),
                ("winner", models.CharField(blank=True, default="", max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="event.eventschedulesection",
                    ),
                ),
            ],
            options={
                "ordering": ["section__display_order", "display_order", "track_number"],
            },
        ),
        migrations.CreateModel(
            name="EventScheduleSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("slot_order", models.PositiveIntegerField()),
                ("is_break", models.BooleanField(default=False)),
                (
                    "year_semester",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("class_code", models.CharField(blank=True, default="", max_length=32)),
                (
                    "team_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("team_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "project_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "organization",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("industry", models.CharField(blank=True, default="", max_length=100)),
                ("abstract", models.TextField(blank=True, default="")),
                ("student_names", models.TextField(blank=True, default="")),
                (
                    "name_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "display_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_schedule_slots",
                        to="projects.project",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="event.eventscheduletrack",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "track__section__display_order",
                    "track__display_order",
                    "slot_order",
                ],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("text", models.CharField(max_length=500)),
                ("is_required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationSheetSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("append", "Append Row"), ("full", "Full Sync")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("rows_written", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheet_sync_logs",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "barcode",
                    models.CharField(
                        default=event.models.registration.ticket.generate_barcode,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "ticket_code",
                    models.CharField(
                        default=event.models.registration.registration.generate_registration_ticket_code,
                        editable=False,
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "attendee_first_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "attendee_last_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "attendee_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "attendee_secondary_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "attendee_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("phone_verified", models.BooleanField(default=False)),
                (
                    "attendee_organization",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "question_answers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Stored answers for event registration questions.",
                    ),
                ),
                (
                    "ticket_email_sent_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("ticket_email_error", models.TextField(blank=True, default="")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="event.event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="event.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventAgendaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[("expo", "Expo"), ("awards", "Awards & Reception")],
                        max_length=20,
                    ),
                ),
                ("time_label", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_items",
                        to="event.currentprojectschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["section_type", "display_order", "time_label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("config", "section_type", "display_order"),
                        name="unique_agenda_order_per_config_section",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CheckInRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="event.checkin",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in_records",
                        to="event.eventregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("check_in", "registration"),
                        name="unique_checkin_per_registration",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="eventschedulesection",
            constraint=models.UniqueConstraint(
                fields=("config", "code"), name="unique_schedule_section_per_config"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventscheduletrack",
            constraint=models.UniqueConstraint(
                fields=("section", "track_number"),
                name="unique_track_number_per_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventscheduletrack",
            constraint=models.UniqueConstraint(
                fields=("section", "display_order"),
                name="unique_track_order_per_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventscheduleslot",
            constraint=models.UniqueConstraint(
                fields=("track", "slot_order"), name="unique_slot_order_per_track"
            ),
        ),
        migrations.AddIndex(
            model_name="registrationsheetsynclog",
            index=models.Index(
                fields=["event", "created_at"], name="event_regis_event_i_060ed2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["member", "created_at"], name="event_event_member__27d860_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["event", "created_at"], name="event_event_event_i_5ec1f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["ticket_code"], name="event_event_ticket__f78c13_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventregistration",
            constraint=models.UniqueConstraint(
                fields=("member", "event"), name="unique_event_registration_per_member"
            ),
        ),
    ]
