# Generated by Django 5.2.10 on 2026-04-21 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _null_stale_slot_project_fks(apps, schema_editor):
    """Drop stale ``EventScheduleSlot.project`` references before retargeting the FK.

    The original FK pointed to ``projects.Project``. This migration retargets
    it to ``event.CurrentProject`` (a new table). Any already-populated
    ``project_id`` values are UUIDs from ``projects.Project`` that will not
    exist in ``event.CurrentProject``, so the new FK constraint would fail
    to apply in environments with existing data. Nulling those values is
    safe because the field is ``null=True, on_delete=SET_NULL`` — the slots
    keep their display_text/code and simply have no linked project row
    until the next schedule sync repopulates them.
    """
    EventScheduleSlot = apps.get_model("event", "EventScheduleSlot")
    EventScheduleSlot.objects.exclude(project_id=None).update(project_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentprojectschedule",
            name="auto_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Automatically sync from Google Sheets on a schedule.",
                verbose_name="Auto Sync",
            ),
        ),
        migrations.AddField(
            model_name="currentprojectschedule",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="currentprojectschedule",
            name="sync_interval_minutes",
            field=models.PositiveIntegerField(
                default=60,
                help_text="How often to auto-sync, in minutes. Used by the sync_schedule management command.",
                verbose_name="Sync Interval (minutes)",
            ),
        ),
        migrations.CreateModel(
            name="CurrentProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "class_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "team_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("team_name", models.CharField(blank=True, default="", max_length=255)),
                ("project_title", models.CharField(max_length=500)),
                (
                    "organization",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("abstract", models.TextField(blank=True, default="")),
                ("student_names", models.TextField(blank=True, default="")),
                ("is_presenting", models.BooleanField(db_index=True, default=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="event.currentprojectschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Current Project",
                "ordering": ["class_code", "team_number"],
                "unique_together": {("schedule", "team_number", "project_title")},
            },
        ),
        migrations.RunPython(_null_stale_slot_project_fks, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="eventscheduleslot",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule_slots",
                to="event.currentproject",
            ),
        ),
    ]
