# Generated by Django 5.2.10 on 2026-04-22 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_currentprojectschedule_auto_sync_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("manual", "Manual Pull"), ("auto", "Auto Sync")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("sections_created", models.PositiveIntegerField(default=0)),
                ("tracks_created", models.PositiveIntegerField(default=0)),
                ("slots_created", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="event.currentprojectschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Sync Log",
                "verbose_name_plural": "Schedule Sync Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
