# Generated by Django 5.2.10 on 2026-04-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailauthchallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("login", "Login"),
                    ("password_reset", "Password Reset"),
                    ("password_change", "Password Change"),
                    ("account_delete", "Account Delete"),
                    ("contact_email_verify", "Contact Email Verify"),
                    ("admin_login", "Admin Login"),
                ],
                max_length=32,
            ),
        ),
    ]
