# Generated by Django 5.2.10 on 2026-04-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0002_alter_emailauthchallenge_purpose"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="email_subscribe",
        ),
    ]
