# Generated by Django 5.2.10 on 2026-04-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0003_remove_member_email_subscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Job title or position within the organization",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
    ]
