# Generated by Django 5.2.10 on 2026-04-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0005_encrypt_rsa_private_keys"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contactemail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email_type", "primary")),
                fields=("member",),
                name="one_primary_email_per_member",
            ),
        ),
    ]
