# Generated by Django 5.2.10 on 2026-04-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0006_contactemail_one_primary_email_per_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactemail",
            name="subscribe",
            field=models.BooleanField(
                default=True,
                help_text="Whether the email is subscribed to communications",
                verbose_name="Subscribed",
            ),
        ),
    ]
