# Generated by Django 5.2.10 on 2026-04-10 17:27

import authn.models.security.impersonation_token
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0007_alter_contactemail_subscribe_default_true"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpersonationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "token",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=authn.models.security.impersonation_token.default_expiry
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The admin who initiated the impersonation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_tokens_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The member being impersonated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
