# Generated by Django 5.2.10 on 2026-04-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0008_impersonationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactphone",
            name="phone_number",
            field=models.CharField(
                help_text="National digits only (e.g. 2095765113)",
                max_length=20,
                unique=True,
            ),
        ),
    ]
