# Generated by Django 5.2.10 on 2026-04-21 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0009_alter_contactphone_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberSheetSyncConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable automatic member-to-sheet sync.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "google_sheet_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The spreadsheet ID from the Google Sheets URL.",
                        max_length=255,
                        verbose_name="Google Sheet ID",
                    ),
                ),
                (
                    "worksheet_gid",
                    models.IntegerField(
                        blank=True,
                        help_text="Target worksheet GID. Leave blank to use the first sheet.",
                        null=True,
                        verbose_name="Worksheet GID",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Synced At"
                    ),
                ),
                (
                    "sync_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Last Sync Row Count"
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True, default="", verbose_name="Last Sync Error"
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Sheet Sync Config",
                "verbose_name_plural": "Member Sheet Sync Configs",
            },
        ),
        migrations.CreateModel(
            name="MemberSheetSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("debounced", "Debounced"),
                            ("full", "Full Sync"),
                            ("scheduled", "Scheduled"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("rows_written", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
