# Generated by Django 5.2.10 on 2026-04-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0010_membersheetsyncconfig_membersheetsynclog"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersheetsyncconfig",
            name="auto_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Automatically sync to the sheet when a member is created or updated.",
                verbose_name="Auto Sync",
            ),
        ),
        migrations.AlterField(
            model_name="membersheetsyncconfig",
            name="is_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable member-to-sheet sync (manual sync and management command).",
                verbose_name="Enabled",
            ),
        ),
    ]
