# Generated by Django 5.2.10 on 2026-04-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0011_membersheetsyncconfig_auto_sync_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membersheetsyncconfig",
            name="auto_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Automatically sync to the sheet when a member, contact email, or contact phone is created, updated, or deleted. Each Gunicorn worker debounces independently — in multi-worker deployments, bursts of writes may produce one sync per worker.",
                verbose_name="Auto Sync",
            ),
        ),
    ]
