# Generated by Django 5.2.14 on 2026-06-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0012_alter_membersheetsyncconfig_auto_sync_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="admin_apps",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Django apps this admin may manage (e.g. ["cms", "event"]). Superusers ignore this.',
                verbose_name="Admin apps",
            ),
        ),
    ]
