# Generated by Django 5.2.10 on 2026-06-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0013_member_admin_apps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactphone",
            name="region",
            field=models.CharField(
                choices=[("1-US", "United States")],
                default="1-US",
                help_text="Region of the phone number",
                max_length=20,
            ),
        ),
    ]
