# Generated by Django 5.2.15 on 2026-06-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0014_alter_contactphone_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailauthchallenge",
            name="channel",
            field=models.CharField(
                choices=[("email", "Email"), ("sms", "SMS")],
                default="email",
                help_text="Delivery channel the verification code was sent through.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="emailauthchallenge",
            name="target_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="E.164 phone number where the verification code was sent (SMS channel).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailauthchallenge",
            name="code_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hashed verification code. Blank for SMS-channel rows, whose code lives in the OTP cache.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="emailauthchallenge",
            name="target_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email address where the verification code was sent (email channel).",
                max_length=254,
            ),
        ),
    ]
