# Generated by Django 5.2.10 on 2026-04-06 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PastProjectShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("rows", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("year", models.PositiveIntegerField(db_index=True)),
                (
                    "season",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Spring"), (2, "Fall")], db_index=True
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=50)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["-year", "-season"],
                "unique_together": {("year", "season")},
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "class_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "team_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("team_name", models.CharField(blank=True, default="", max_length=255)),
                ("project_title", models.CharField(max_length=500)),
                (
                    "organization",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("abstract", models.TextField(blank=True, default="")),
                ("student_names", models.TextField(blank=True, default="")),
                ("track", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "presentation_order",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="projects.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["semester", "class_code", "team_number"],
                "indexes": [
                    models.Index(
                        fields=["semester", "class_code"],
                        name="projects_pr_semeste_210a95_idx",
                    ),
                    models.Index(
                        fields=["semester", "track", "presentation_order"],
                        name="projects_pr_semeste_6bf542_idx",
                    ),
                ],
            },
        ),
    ]
