# Generated by Django 5.2.14 on 2026-06-05 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastProjectsSheetConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Config Name",
                    ),
                ),
                (
                    "sheet_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The spreadsheet ID containing past-project rows (the part of the URL after /d/).",
                        max_length=255,
                        verbose_name="Google Sheet ID",
                    ),
                ),
                (
                    "worksheet_name",
                    models.CharField(
                        blank=True,
                        default="Past-Projects-WEB-LIVE",
                        help_text="The tab/worksheet name to read (e.g. 'Past-Projects-WEB-LIVE').",
                        max_length=255,
                        verbose_name="Worksheet Name",
                    ),
                ),
                (
                    "auto_sync_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically sync from Google Sheets on a schedule.",
                        verbose_name="Auto Sync",
                    ),
                ),
                (
                    "sync_interval_minutes",
                    models.PositiveIntegerField(
                        default=1440,
                        help_text="How often to auto-sync, in minutes. Used by the sync_past_projects management command.",
                        verbose_name="Sync Interval (minutes)",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("sync_error", models.TextField(blank=True, default="")),
                (
                    "sync_count",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        verbose_name="Projects Synced (last run)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Past Projects Sheet",
                "verbose_name_plural": "Past Projects Sheet",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual / CSV"), ("sheet", "Google Sheet")],
                db_index=True,
                default="manual",
                help_text="Where this row came from. Google-Sheet-synced rows are replaced on every sync; manual/CSV rows are never touched by the sync.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PastProjectSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("manual", "Manual Pull"), ("auto", "Auto Sync")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("rows_read", models.PositiveIntegerField(default=0)),
                ("projects_created", models.PositiveIntegerField(default=0)),
                ("semesters_touched", models.PositiveIntegerField(default=0)),
                ("rows_skipped", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="projects.pastprojectssheetconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Past Project Sync Log",
                "verbose_name_plural": "Past Project Sync Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
