# Generated by Django 5.2.14 on 2026-06-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_pastprojectshare_created_by_pastprojectshare_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastprojectshare",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
