# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_pastprojectshare_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastprojectshare",
            name="details_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
