# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_pastprojectshare_details_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastprojectsynclog",
            name="projects_deleted",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pastprojectsynclog",
            name="projects_updated",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
