# Generated by Django 5.2.10 on 2026-04-09 06:57

import cms.models.media
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsasset",
            name="file",
            field=models.FileField(
                upload_to=cms.models.media.asset_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "gif", "webp", "svg", "pdf"]
                    ),
                    cms.models.media.validate_asset_file_type,
                ],
            ),
        ),
    ]
