# Generated by Django 5.2.10 on 2026-04-16 00:32

import cms.models.content.layout.site_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_alter_cmsasset_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="StyleSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Machine-readable identifier (e.g. 'global', 'cms-blocks', 'page-news').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal note about what this sheet covers.",
                    ),
                ),
                (
                    "css",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Raw CSS injected into the page. Uses ITG design-token variables (--itg-*).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Lower numbers load first. Global sheets should be < 100, page sheets >= 100.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Style Sheet",
                "verbose_name_plural": "Style Sheets",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="cmspage",
            name="page_css",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom CSS injected when this page is loaded. Scoped to the page wrapper.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="design_tokens",
            field=models.JSONField(
                default=cms.models.content.layout.site_settings.default_design_tokens,
                help_text="Structured design tokens (colors, typography, layout) served to the frontend as CSS custom properties.",
            ),
        ),
    ]
