# Generated by Django 5.2.10 on 2026-04-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_populate_stylesheets"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmsblock",
            name="embed_slug",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unique kebab-case slug used in the embed URL (e.g. 'contact-form-2026').",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="cmsblock",
            name="is_embeddable",
            field=models.BooleanField(
                default=False,
                help_text="Allow this block to be embedded by third-party sites via iframe.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cmsblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_embeddable", True)),
                fields=("embed_slug",),
                name="unique_embed_slug_when_enabled",
            ),
        ),
    ]
