# Generated by Django 5.2.10 on 2026-04-17 02:20

import django.core.serializers.json
from django.db import migrations, models


def copy_block_embeds_to_page_configs(apps, schema_editor):
    """Convert each embeddable block into a single-block entry on its page's embed_configs."""
    CMSBlock = apps.get_model("cms", "CMSBlock")
    CMSPage = apps.get_model("cms", "CMSPage")

    pages_to_save: dict = {}
    for block in CMSBlock.objects.filter(is_embeddable=True).exclude(embed_slug=""):
        page = pages_to_save.get(block.page_id)
        if page is None:
            page = CMSPage.objects.get(pk=block.page_id)
            pages_to_save[block.page_id] = page
        configs = list(page.embed_configs or [])
        # Skip if another block already contributed this slug (shouldn't happen
        # thanks to the old unique constraint, but stay defensive).
        if any((entry or {}).get("slug") == block.embed_slug for entry in configs):
            continue
        configs.append(
            {
                "slug": block.embed_slug,
                "admin_label": block.admin_label or "",
                "block_sort_orders": [block.sort_order],
            }
        )
        page.embed_configs = configs

    for page in pages_to_save.values():
        page.save(update_fields=["embed_configs"])


def noop_reverse(apps, schema_editor):
    # Best-effort: the old fields don't exist in the forward state, so reversing
    # this data step is a no-op. The schema reversal happens separately.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_cmsblock_embed_slug_cmsblock_is_embeddable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmspage",
            name="embed_configs",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="List of embed widget configurations. Each entry is a dict with keys 'slug' (unique kebab-case global identifier), 'block_sort_orders' (list of block sort_orders to include in that embed), and optionally 'admin_label'.",
            ),
        ),
        migrations.RunPython(copy_block_embeds_to_page_configs, noop_reverse),
        migrations.RemoveConstraint(
            model_name="cmsblock",
            name="unique_embed_slug_when_enabled",
        ),
        migrations.RemoveField(
            model_name="cmsblock",
            name="embed_slug",
        ),
        migrations.RemoveField(
            model_name="cmsblock",
            name="is_embeddable",
        ),
    ]
