# Generated by Django 5.2.10 on 2026-04-23 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_cms_embed_widget"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmsembedwidget",
            name="app_route",
            field=models.CharField(
                blank=True,
                default="",
                help_text="App route path (e.g. /schedule) for 'app_route' widgets.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="cmsembedwidget",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("blocks", "CMS Page Blocks"),
                    ("app_route", "App Route (interactive page)"),
                ],
                default="blocks",
                help_text="Whether this widget embeds CMS blocks or a full app-route page (e.g. /schedule).",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="cmsembedwidget",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text="Source page for 'blocks' widgets. Leave blank for 'app_route' widgets.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embed_widgets",
                to="cms.cmspage",
            ),
        ),
    ]
