# Generated by Django 5.2.10 on 2026-04-23 21:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_app_route_embed"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMSEmbedAllowedHost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "hostname",
                    models.CharField(
                        help_text="Exact host like 'docs.google.com' or wildcard like '*.youtube.com'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "CMS Embed Allowed Host",
                "verbose_name_plural": "CMS Embed Allowed Hosts",
                "db_table": "cms_cmsembedallowedhost",
                "ordering": ["hostname"],
            },
        ),
        migrations.AlterField(
            model_name="cmsblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero Banner"),
                    ("rich_text", "Rich Text"),
                    ("faq_list", "FAQ List"),
                    ("link_list", "Link List"),
                    ("cta_group", "CTA Buttons"),
                    ("image_text", "Image + Text"),
                    ("notice", "Notice / Callout"),
                    ("contact_info", "Contact Info"),
                    ("section_group", "Section Group"),
                    ("table", "Data Table"),
                    ("numbered_list", "Numbered List"),
                    ("proposal_cards", "Proposal Cards"),
                    ("navigation_grid", "Navigation Grid"),
                    ("sponsor_year", "Sponsor Year"),
                    ("embed", "Embed (iframe)"),
                ],
                max_length=30,
            ),
        ),
    ]
