# Generated by Django 5.2.10 on 2026-04-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_seed_embed_allowed_hosts"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmsembedwidget",
            name="hide_section_titles",
            field=models.BooleanField(
                default=False,
                help_text="Hide `.section-title` headings when this widget renders inside the embed iframe.",
            ),
        ),
        migrations.AlterField(
            model_name="cmsblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero Banner"),
                    ("rich_text", "Rich Text"),
                    ("faq_list", "FAQ List"),
                    ("link_list", "Link List"),
                    ("cta_group", "CTA Buttons"),
                    ("image_text", "Image + Text"),
                    ("notice", "Notice / Callout"),
                    ("contact_info", "Contact Info"),
                    ("section_group", "Section Group"),
                    ("table", "Data Table"),
                    ("numbered_list", "Numbered List"),
                    ("proposal_cards", "Proposal Cards"),
                    ("navigation_grid", "Navigation Grid"),
                    ("sponsor_year", "Sponsor Year"),
                    ("embed", "Embed (iframe)"),
                    ("embed_widget", "Embed CMS Widget"),
                ],
                max_length=30,
            ),
        ),
    ]
