# Generated by Django 5.2.10 on 2026-05-08 01:28

import cms.models.media
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0013_cmspage_embed_widget_hidden_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsasset",
            name="file",
            field=models.FileField(
                upload_to=cms.models.media.asset_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "png",
                            "jpg",
                            "jpeg",
                            "gif",
                            "webp",
                            "svg",
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                            "csv",
                            "txt",
                        ]
                    ),
                    cms.models.media.validate_asset_file_size,
                    cms.models.media.validate_asset_file_type,
                ],
            ),
        ),
    ]
