# Generated by Cursor on 2026-05-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0014_alter_cmsasset_file"),
        ("event", "0004_checkin_event_wide_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmsembedwidget",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional schedule to render when embedding the /schedule app route.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cms_embed_widgets",
                to="event.currentprojectschedule",
            ),
        ),
    ]
