# Generated by Django 5.2.10 on 2026-05-16 21:01

import django.db.models.deletion
import system_intelligence.models.export
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0021_remove_chatconversation_context_summary_through_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemIntelligenceConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        default="Default",
                        help_text="A label to identify this configuration.",
                        max_length=128,
                        verbose_name="Config Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one config can be active. Activating this will deactivate others.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        default="You are a helpful AI assistant for the Innovate to Grow admin team. You have access to the application database and can query members, events, registrations, projects, email campaigns, CMS pages, news articles, and analytics data. Use the available tools to look up data when answering questions. Always verify facts by querying the database rather than guessing.",
                        verbose_name="System Prompt",
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=4096,
                        help_text="Maximum number of tokens in the model response.",
                        verbose_name="Max Tokens",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Sampling temperature (0.0 = deterministic, 1.0 = creative).",
                        verbose_name="Temperature",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Intelligence Config",
                "verbose_name_plural": "System Intelligence Configs",
            },
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(default="New Chat", max_length=200)),
                (
                    "auto_title",
                    models.BooleanField(
                        default=True,
                        help_text="True until the title has been explicitly set, either by the user or by the first-turn auto-rename.",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("normal", "Normal"), ("plan", "Plan-only")],
                        default="normal",
                        help_text="Plan mode disables write tools and steers the agent toward planning only.",
                        max_length=16,
                    ),
                ),
                (
                    "context_summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Rolling summary of older System Intelligence conversation context.",
                    ),
                ),
                (
                    "context_summary_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "model_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The Bedrock model that produced this response (for audit).",
                        max_length=256,
                        verbose_name="Model ID",
                    ),
                ),
                (
                    "tool_calls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Bedrock tool invocations for this assistant turn (name, input, result preview).",
                    ),
                ),
                (
                    "token_usage",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Token consumption for this turn (inputTokens, outputTokens, totalTokens).",
                    ),
                ),
                (
                    "context_usage",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Estimated context prepared for this turn before invoking the model.",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="system_intelligence.chatconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="context_summary_through_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Newest message included in the rolling context summary.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="system_intelligence.chatmessage",
            ),
        ),
        migrations.CreateModel(
            name="SystemIntelligenceExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(default="Export", max_length=200)),
                ("filename", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(
                        upload_to=system_intelligence.models.export._export_upload_to
                    ),
                ),
                (
                    "model_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("field_names", models.JSONField(blank=True, default=list)),
                ("row_count", models.PositiveIntegerField(default=0)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="system_intelligence.chatconversation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_intelligence_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Intelligence Export",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemIntelligenceActionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("cms_page_update", "CMS page update"),
                            ("db_create", "Database create"),
                            ("db_update", "Database update"),
                            ("db_delete", "Database delete"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "target_app_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("target_pk", models.CharField(blank=True, default="", max_length=128)),
                (
                    "target_repr",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("before_snapshot", models.JSONField(blank=True, default=dict)),
                ("after_snapshot", models.JSONField(blank=True, default=dict)),
                ("diff", models.JSONField(blank=True, default=list)),
                (
                    "preview_token",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "preview_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("preview_expires_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assistant_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_requests",
                        to="system_intelligence.chatmessage",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_requests",
                        to="system_intelligence.chatconversation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_intelligence_action_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_system_intelligence_action_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Intelligence Action Request",
                "verbose_name_plural": "System Intelligence Action Requests",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"],
                        name="system_inte_convers_95b2f2_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="system_inte_status_293395_idx",
                    ),
                ],
            },
        ),
    ]
