# Generated by Cursor on 2026-05-22

from django.db import migrations, models


DEFAULT_MODEL_ID = "us.anthropic.claude-sonnet-4-20250514-v1:0"


def copy_aws_default_model_to_system_configs(apps, _schema_editor):
    AWSCredentialConfig = apps.get_model("core", "AWSCredentialConfig")
    SystemIntelligenceConfig = apps.get_model("system_intelligence", "SystemIntelligenceConfig")

    source = (
        AWSCredentialConfig.objects.filter(is_active=True)
        .exclude(default_model_id="")
        .order_by("-updated_at")
        .first()
    )
    if source is None:
        source = AWSCredentialConfig.objects.exclude(default_model_id="").order_by("-updated_at").first()
    if source is None:
        return

    SystemIntelligenceConfig.objects.all().update(default_model_id=source.default_model_id)


def copy_system_default_model_to_aws_configs(apps, _schema_editor):
    AWSCredentialConfig = apps.get_model("core", "AWSCredentialConfig")
    SystemIntelligenceConfig = apps.get_model("system_intelligence", "SystemIntelligenceConfig")

    source = (
        SystemIntelligenceConfig.objects.filter(is_active=True)
        .exclude(default_model_id="")
        .order_by("-updated_at")
        .first()
    )
    if source is None:
        source = SystemIntelligenceConfig.objects.exclude(default_model_id="").order_by("-updated_at").first()
    if source is None:
        return

    AWSCredentialConfig.objects.all().update(default_model_id=source.default_model_id)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_chatconversation_context_summary_through_message_and_more"),
        ("system_intelligence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemintelligenceconfig",
            name="default_model_id",
            field=models.CharField(
                blank=True,
                default=DEFAULT_MODEL_ID,
                help_text="Site-wide default Bedrock model or inference profile ID.",
                max_length=256,
                verbose_name="Default AI Model",
            ),
        ),
        migrations.RunPython(copy_aws_default_model_to_system_configs, copy_system_default_model_to_aws_configs),
    ]
