# Generated by Django 5.2.14 on 2026-06-07 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "system_intelligence",
            "0003_systemintelligenceconfig_public_assistant_enabled_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="systemintelligenceconfig",
            name="public_assistant_log_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Persist public chat and AI-search turns for admin audit. Failures never affect the visitor.",
                verbose_name="Public Assistant Audit Logging",
            ),
        ),
        migrations.AddField(
            model_name="systemintelligenceconfig",
            name="public_assistant_log_retention_days",
            field=models.PositiveIntegerField(
                default=90,
                help_text="Days to keep audited conversations before the cleanup command deletes them. 0 keeps forever.",
                verbose_name="Public Assistant Log Retention (days)",
            ),
        ),
        migrations.CreateModel(
            name="AssistantConversationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("public_chat", "Public Chat"),
                            ("ai_search", "AI Search"),
                        ],
                        db_index=True,
                        help_text="Which audited endpoint produced this conversation.",
                        max_length=20,
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Client-supplied conversation id (untrusted). Null for ungrouped turns.",
                        null=True,
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Salted SHA-256 hash of the visitor IP (never the raw IP).",
                        max_length=64,
                    ),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Denormalized count of turns recorded in this conversation.",
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Denormalized sum of totalTokens across this conversation's turns.",
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Timestamp of the most recent recorded turn.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated member, when the request was authenticated.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistant Conversation Log",
                "verbose_name_plural": "Assistant Conversation Logs",
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantMessageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "prompt",
                    models.TextField(
                        help_text="The visitor's question or search query."
                    ),
                ),
                (
                    "reply",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The assistant's reply text (empty for AI search).",
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Compact result payload (e.g. AI-search project matches).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("error", "Error"),
                            ("budget", "Budget exceeded"),
                            ("unavailable", "Unavailable"),
                        ],
                        db_index=True,
                        help_text="Terminal outcome of the turn.",
                        max_length=16,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The Bedrock model/inference profile used for this turn.",
                        max_length=256,
                        verbose_name="Model ID",
                    ),
                ),
                (
                    "token_usage",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Token consumption for this turn (inputTokens, outputTokens, totalTokens).",
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Wall-clock latency of the model call in milliseconds.",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="system_intelligence.assistantconversationlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistant Message Log",
                "verbose_name_plural": "Assistant Message Logs",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="assistantconversationlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_id__isnull", False)),
                fields=("source", "session_id"),
                name="uniq_assistant_log_source_session",
            ),
        ),
        migrations.AddIndex(
            model_name="assistantmessagelog",
            index=models.Index(
                fields=["status", "created_at"], name="system_inte_status_9e6eff_idx"
            ),
        ),
    ]
