"""Template generation for member import spreadsheets."""

from __future__ import annotations

from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side


def generate_template_excel() -> bytes:
    """Generate a template Excel file for member import."""
    workbook = Workbook()
    worksheet = workbook.active
    worksheet.title = "Members"

    headers = [
        ("first_name", "First Name", 15),
        ("last_name", "Last Name", 15),
        ("middle_name", "Middle Name", 15),
        ("title", "Title", 20),
        ("when_started", "When Started", 15),
        ("last_updated", "Last Updated", 15),
        ("primary_email", "Primary Email", 30),
        ("primary_verified", "Primary Verified", 16),
        ("primary_subscribed", "Primary Subscribed", 18),
        ("primary_expired", "Primary Expired", 16),
        ("secondary_email", "Secondary Email", 30),
        ("secondary_verified", "Secondary Verified", 18),
        ("secondary_subscribed", "Secondary Subscribed", 20),
        ("phone_number", "Phone Number", 18),
        ("phone_subscribed", "Phone Subscribed", 18),
        ("phone_verified", "Phone Verified", 18),
        ("organization", "Organization (optional)", 25),
    ]
    _apply_headers(worksheet, headers)
    _apply_example_row(worksheet)
    _apply_instruction_sheet(workbook)

    output = BytesIO()
    workbook.save(output)
    output.seek(0)
    return output.getvalue()


def _apply_headers(worksheet, headers):
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_alignment = Alignment(horizontal="center", vertical="center")
    thin_border = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin"),
    )

    for column, (_field, label, width) in enumerate(headers, 1):
        cell = worksheet.cell(row=1, column=column, value=label)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment
        cell.border = thin_border
        worksheet.column_dimensions[cell.column_letter].width = width


def _apply_example_row(worksheet):
    thin_border = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin"),
    )
    example_data = [
        "John",
        "Doe",
        "Michael",
        "Research Assistant",
        "2024-01-15",
        "2024-06-01",
        "john.doe@example.com",
        "TRUE",
        "TRUE",
        "FALSE",
        "john.d@gmail.com",
        "FALSE",
        "FALSE",
        "+12095551234",
        "TRUE",
        "FALSE",
        "UC Merced",
    ]
    for column, value in enumerate(example_data, 1):
        worksheet.cell(row=2, column=column, value=value).border = thin_border


def _apply_instruction_sheet(workbook):
    instructions_sheet = workbook.create_sheet(title="Instructions")
    instructions = [
        ("Field Descriptions", ""),
        ("", ""),
        ("First Name", "Member's first name"),
        ("Last Name", "Member's last name"),
        ("Middle Name", "Member's middle name (optional)"),
        ("Title", "Member's title or role (optional)"),
        ("When Started", "Date the member joined (YYYY-MM-DD or MM/DD/YYYY)"),
        ("Last Updated", "Last update date (informational only, not imported)"),
        ("Primary Email", "Primary email address (REQUIRED - used as login email)"),
        ("Primary Verified", "Whether the primary email is verified (TRUE/FALSE)"),
        ("Primary Subscribed", "Whether the primary email is subscribed (TRUE/FALSE)"),
        ("Primary Expired", "Whether the primary email has expired (informational only)"),
        ("Secondary Email", "Secondary/alternate email address (optional)"),
        ("Secondary Verified", "Whether the secondary email is verified (TRUE/FALSE)"),
        ("Secondary Subscribed", "Whether the secondary email is subscribed (TRUE/FALSE)"),
        ("Phone Number", "Phone number in E.164 format, e.g. +12095551234 (optional)"),
        ("Phone Subscribed", "Whether the phone is subscribed (TRUE/FALSE)"),
        ("Phone Verified", "Whether the phone is verified (TRUE/FALSE)"),
        ("Organization (optional)", "Organization or company name"),
        ("", ""),
        ("Notes", ""),
        ("", "UUID is auto-generated by the system for each new member"),
        ("", "Username is auto-generated from the primary email address"),
        ("", "A random password is generated unless a default is specified"),
        ("", "Existing members can be updated if matched by primary email and updates are enabled"),
        ("", "'Last Updated' and 'Primary Expired' are informational only"),
    ]
    for row, (col1, col2) in enumerate(instructions, 1):
        instructions_sheet.cell(row=row, column=1, value=col1)
        instructions_sheet.cell(row=row, column=2, value=col2)
    instructions_sheet.column_dimensions["A"].width = 25
    instructions_sheet.column_dimensions["B"].width = 60
