# Generated by Django 5.2.10 on 2026-04-06 10:14

import django.db.models.deletion
import mail.models.magic_login
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("subject", models.CharField(max_length=998)),
                (
                    "body",
                    models.TextField(
                        blank=True, default="", verbose_name="Email Content"
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("subscribers", "All Email Subscribers"),
                            ("event_registrants", "Event Registrants"),
                            ("selected_members", "Selected Members"),
                            ("manual", "Manual Emails"),
                        ],
                        default="subscribers",
                        max_length=32,
                    ),
                ),
                (
                    "member_email_scope",
                    models.CharField(
                        choices=[
                            ("primary", "Primary email only"),
                            ("all", "All emails (primary + secondary)"),
                        ],
                        default="primary",
                        help_text="Send to primary email only, or all emails for each member.",
                        max_length=16,
                        verbose_name="Send to",
                    ),
                ),
                (
                    "manual_emails",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="One email per line. Used when audience is 'Manual Emails'.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required when audience is 'Event Registrants'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_campaigns",
                        to="event.event",
                    ),
                ),
                (
                    "selected_members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Pick members when audience is 'Selected Members'.",
                        related_name="selected_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amazon SES Mail",
                "verbose_name_plural": "Amazon SES Mails",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MagicLoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=mail.models.magic_login.default_expiry
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_tokens",
                        to="mail.emailcampaign",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_login_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecipientLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("email_address", models.EmailField(max_length=254)),
                (
                    "recipient_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=16)),
                ("error_message", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_logs",
                        to="mail.emailcampaign",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipient Log",
                "verbose_name_plural": "Recipient Logs",
                "ordering": ["-sent_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "email_address"),
                        name="unique_campaign_recipient",
                    )
                ],
            },
        ),
    ]
