# Generated by Django 5.2.10 on 2026-04-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_emailcampaign_login_redirect_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="login_redirect_path",
            field=models.CharField(
                default="/account",
                help_text="Internal site page where recipients land after one-click login.",
                max_length=200,
                verbose_name="Post-login destination",
            ),
        ),
    ]
