# Generated by Django 5.2.10 on 2026-04-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_alter_emailcampaign_login_redirect_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="include_unsubscribe_header",
            field=models.BooleanField(
                default=True,
                help_text="Add RFC 8058 List-Unsubscribe headers so recipients can unsubscribe directly from their email client.",
                verbose_name="Include one-click unsubscribe",
            ),
        ),
    ]
