# Generated by Django 5.2.10 on 2026-04-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_emailcampaign_include_unsubscribe_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="audience_type",
            field=models.CharField(
                choices=[
                    ("subscribers", "All Email Subscribers"),
                    ("event_registrants", "Event Registrants"),
                    ("ticket_type", "Event Ticket Type"),
                    ("checked_in", "Checked-In Attendees"),
                    ("not_checked_in", "No-Shows (Not Checked In)"),
                    ("all_members", "All Active Members"),
                    ("staff", "Staff Members"),
                    ("selected_members", "Selected Members"),
                    ("manual", "Manual Emails"),
                ],
                default="subscribers",
                max_length=32,
            ),
        ),
    ]
