# Generated by Django 5.2.10 on 2026-04-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0005_align_audience_type_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="error_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Top-level error when the campaign fails before or during sending.",
            ),
        ),
    ]
