# Generated by Django 5.2.10 on 2026-04-12 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0006_emailcampaign_error_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipientlog",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Recipient Log",
                "verbose_name_plural": "Recipient Logs",
            },
        ),
    ]
