# Generated by Django 5.2.10 on 2026-04-21 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_currentprojectschedule_auto_sync_enabled_and_more"),
        ("mail", "0008_emailcampaign_audience_exclusion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="exclude_audience_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No exclusion"),
                    ("subscribers", "All Email Subscribers"),
                    ("event_registrants", "Event Registrants"),
                    ("ticket_type", "Event Ticket Type"),
                    ("checked_in", "Checked-In Attendees"),
                    ("not_checked_in", "No-Shows (Not Checked In)"),
                    ("all_members", "All Active Members"),
                    ("staff", "Staff Members"),
                    ("selected_members", "Selected Members"),
                ],
                default="",
                help_text="Remove anyone whose address appears in this group from the final list (case-insensitive). Member-based exclusion uses the same \"Send to\" rule as above. Event-based exclusion uses each registration's attendee email, or the member's primary email if the attendee email is empty.",
                max_length=32,
                verbose_name="Exclude audience",
            ),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="exclude_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Event used to build the exclusion list when the exclude audience is event-based.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="event.event",
            ),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="exclude_members",
            field=models.ManyToManyField(
                blank=True,
                help_text='When exclude audience is "Selected Members", these people are dropped using the same "Send to" addresses as for a primary selected-members audience.',
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="member_email_scope",
            field=models.CharField(
                choices=[
                    ("primary", "Primary email only"),
                    ("all", "All emails (primary + secondary + other)"),
                ],
                default="primary",
                help_text="For member-based audiences (subscribers, all active members, staff, selected members): send only to each person’s primary contact email, or to every saved contact email (primary, secondary, and other). The same choice applies when the exclude audience is one of those member-based types. Event-based audiences (registrants, ticket, checked-in, no-shows) always use the registration’s attendee email when set, otherwise the member’s primary email.",
                max_length=16,
                verbose_name="Send to",
            ),
        ),
    ]
