# Generated by Django 5.2.10 on 2026-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0009_alter_emailcampaign_exclude_audience_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="exclude_member_email_scope",
            field=models.CharField(
                choices=[
                    ("primary", "Primary email only"),
                    ("all", "All emails (primary + secondary + other)"),
                ],
                default="primary",
                help_text="When the exclude audience is member-based (subscribers, all active members, staff, selected members), choose whether exclusion matches only primary emails, or all saved contact emails (primary, secondary, and other). Event-based exclusions always use attendee email (or member primary).",
                max_length=16,
                verbose_name="Exclude send to",
            ),
        ),
    ]
