# Generated by Django 5.2.10 on 2026-04-21 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0010_emailcampaign_exclude_member_email_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="exclude_audience_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No exclusion"),
                    ("subscribers", "All Email Subscribers"),
                    ("event_registrants", "Event Registrants"),
                    ("ticket_type", "Event Ticket Type"),
                    ("checked_in", "Checked-In Attendees"),
                    ("not_checked_in", "No-Shows (Not Checked In)"),
                    ("all_members", "All Active Members"),
                    ("staff", "Staff Members"),
                    ("selected_members", "Selected Members"),
                ],
                default="",
                help_text="Remove anyone whose address appears in this group from the final list (case-insensitive). For member-based exclusions, addresses follow the second \"Send to\" field below. For event-based exclusions, each registration's attendee email, or the member's primary email if the attendee email is empty.",
                max_length=32,
                verbose_name="Exclude audience",
            ),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="exclude_member_email_scope",
            field=models.CharField(
                choices=[
                    ("primary", "Primary email only"),
                    ("all", "All emails (primary + secondary + other)"),
                ],
                default="primary",
                help_text="When the exclude audience is member-based, which of each person's contact emails are used to match against the main recipient list (primary only, or primary + secondary + other). Ignored for event-based exclude audiences (they use attendee or primary as for registrations).",
                max_length=16,
                verbose_name="Send to",
            ),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="exclude_members",
            field=models.ManyToManyField(
                blank=True,
                help_text='When exclude audience is "Selected Members", pick members here; the exclude "Send to" field controls which of their contact emails count for matching.',
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="member_email_scope",
            field=models.CharField(
                choices=[
                    ("primary", "Primary email only"),
                    ("all", "All emails (primary + secondary + other)"),
                ],
                default="primary",
                help_text="For member-based audiences (subscribers, all active members, staff, selected members): send only to each person's primary contact email, or to every saved contact email (primary, secondary, and other). Event-based audiences (registrants, ticket, checked-in, no-shows) use the registration's attendee email when set, otherwise the member's primary email.",
                max_length=16,
                verbose_name="Send to",
            ),
        ),
    ]
