# Generated by Django 5.2.10 on 2026-04-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0011_alter_emailcampaign_exclude_audience_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientlog",
            name="bounce_subtype",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="recipientlog",
            name="bounce_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("Permanent", "Permanent"),
                    ("Transient", "Transient"),
                    ("Undetermined", "Undetermined"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="recipientlog",
            name="bounced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipientlog",
            name="complained_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipientlog",
            name="complaint_feedback_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="recipientlog",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipientlog",
            name="diagnostic_code",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="recipientlog",
            name="last_event_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipientlog",
            name="last_event_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="recipientlog",
            name="last_sns_message_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="recipientlog",
            name="ses_message_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="recipientlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("bounced", "Bounced"),
                    ("complained", "Complained"),
                    ("rejected", "Rejected"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
