# Generated by Django 5.2.10 on 2026-05-25 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_checkin_event_wide_unique"),
        ("mail", "0012_recipientlog_ses_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "message",
                    models.TextField(
                        help_text="Plain text message. Supports {{first_name}}, {{last_name}}, and {{full_name}}. Opt-out wording is not added automatically.",
                        verbose_name="SMS Message",
                    ),
                ),
                (
                    "phone_policy",
                    models.CharField(
                        choices=[
                            ("verified_opt_in", "Verified opt-ins"),
                            ("any_verified", "Any verified phone"),
                        ],
                        default="verified_opt_in",
                        help_text="Verified opt-ins uses verified subscribed contact phones. Any verified also allows verified event registration phones.",
                        max_length=24,
                        verbose_name="Phone eligibility",
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("subscribers", "SMS Subscribers"),
                            ("event_registrants", "Event Registrants"),
                            ("ticket_type", "Event Ticket Type"),
                            ("checked_in", "Checked-In Attendees"),
                            ("not_checked_in", "No-Shows (Not Checked In)"),
                            ("all_members", "All Active Members"),
                            ("staff", "Staff Members"),
                            ("selected_members", "Selected Members"),
                            ("manual", "Manual Phones"),
                        ],
                        default="subscribers",
                        max_length=32,
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ticket UUID when audience is 'Event Ticket Type'.",
                        max_length=64,
                    ),
                ),
                (
                    "manual_phones",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="One E.164 phone number per line, for example +12095551234.",
                    ),
                ),
                (
                    "exclude_audience_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No exclusion"),
                            ("subscribers", "SMS Subscribers"),
                            ("event_registrants", "Event Registrants"),
                            ("ticket_type", "Event Ticket Type"),
                            ("checked_in", "Checked-In Attendees"),
                            ("not_checked_in", "No-Shows (Not Checked In)"),
                            ("all_members", "All Active Members"),
                            ("staff", "Staff Members"),
                            ("selected_members", "Selected Members"),
                        ],
                        default="",
                        help_text="Remove matching phone numbers from the final recipient list.",
                        max_length=32,
                        verbose_name="Exclude audience",
                    ),
                ),
                (
                    "exclude_ticket_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ticket UUID when exclude audience is 'Event Ticket Type'.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Top-level error when the SMS campaign fails before or during sending.",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for event-based SMS audiences.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_campaigns",
                        to="event.event",
                    ),
                ),
                (
                    "exclude_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Event used to build the SMS exclusion list for event-based exclusions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="event.event",
                    ),
                ),
                (
                    "exclude_members",
                    models.ManyToManyField(
                        blank=True,
                        help_text='When exclude audience is "Selected Members", pick members here.',
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Pick members when audience is 'Selected Members'.",
                        related_name="selected_sms_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast SMS",
                "verbose_name_plural": "Broadcast SMS",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmsRecipientLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "recipient_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=16)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "sns_message_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=256
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_logs",
                        to="mail.smscampaign",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Recipient Log",
                "verbose_name_plural": "SMS Recipient Logs",
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "phone_number"),
                        name="unique_sms_campaign_recipient",
                    )
                ],
            },
        ),
    ]
