# Generated by Django 5.2.10 on 2026-06-02 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0013_smscampaign_smsrecipientlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScamDetectorConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        default="Default",
                        help_text="A label to identify this configuration.",
                        max_length=128,
                        verbose_name="Config Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one config can be active. Activating this will deactivate others.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "medium_threshold",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Total signal score at which a message is flagged medium risk.",
                        verbose_name="Medium-risk threshold",
                    ),
                ),
                (
                    "high_threshold",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Total signal score at which a message is flagged high risk.",
                        verbose_name="High-risk threshold",
                    ),
                ),
                (
                    "extra_brands",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Extra brand names to detect impersonation of, one per line.",
                        verbose_name="Additional brands",
                    ),
                ),
                (
                    "trusted_senders",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Email addresses or domains to always treat as safe, one per line (e.g. ucmerced.edu or dean@ucmerced.edu). Skips all scam checks.",
                        verbose_name="Trusted senders",
                    ),
                ),
                (
                    "ai_review_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When on, uncertain (medium-risk) messages are sent to Amazon Bedrock for a second opinion. Requires an active AWS Credential Config. The message body (truncated) is sent to your own AWS account.",
                        verbose_name="Enable AI review",
                    ),
                ),
                (
                    "ai_review_band",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        help_text="Only messages at this rule-based risk level are sent for AI review.",
                        max_length=8,
                        verbose_name="AI review band",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scam Detector Config",
                "verbose_name_plural": "Scam Detector Configs",
            },
        ),
    ]
