# Generated by Codex on 2026-06-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0015_login_link_unification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScamDetectorConfig",
        ),
    ]
