# Generated by Django 5.2.10 on 2026-06-12 02:23

import cms.asset_validation
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CMSAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(
                        upload_to=cms.asset_validation.asset_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "gif",
                                    "webp",
                                    "svg",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                    "csv",
                                    "txt",
                                ]
                            ),
                            cms.asset_validation.validate_asset_file_size,
                            cms.asset_validation.validate_asset_file_type,
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS Asset",
                "verbose_name_plural": "CMS Assets",
                "ordering": ["name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CMSPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "route",
                    models.CharField(
                        help_text="Frontend route path, e.g. '/about'. Must start with '/'.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("meta_description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CMS Page",
                "verbose_name_plural": "CMS Pages",
                "ordering": ["title"],
                "indexes": [
                    models.Index(
                        fields=["route", "status"], name="cms_cmspage_route_08f33c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CMSBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Banner"),
                            ("rich_text", "Rich Text"),
                            ("image_text", "Image + Text"),
                            ("link_list", "Link List"),
                            ("faq_list", "FAQ List"),
                            ("table", "Data Table"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "admin_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Label shown in admin for easier identification.",
                        max_length=200,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="cms.cmspage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Block",
                "verbose_name_plural": "Content Blocks",
                "ordering": ["sort_order"],
                "indexes": [
                    models.Index(
                        fields=["page", "sort_order"],
                        name="cms_cmsbloc_page_id_455329_idx",
                    )
                ],
            },
        ),
    ]
