# Generated by Django 5.2.10 on 2026-04-06 10:14

import core.models.base.service_credentials
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailServiceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default",
                        help_text="A label to identify this configuration (e.g. 'Production SES', 'Dev SMTP').",
                        max_length=128,
                        verbose_name="Config Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one config can be active. Activating this will deactivate others.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "ses_access_key_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AWS access key for SES. Leave blank to skip SES and use SMTP only.",
                        max_length=128,
                        verbose_name="SES Access Key ID",
                    ),
                ),
                (
                    "ses_secret_access_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="SES Secret Access Key",
                    ),
                ),
                (
                    "ses_region",
                    models.CharField(
                        blank=True,
                        default="us-west-2",
                        max_length=32,
                        verbose_name="SES Region",
                    ),
                ),
                (
                    "ses_from_email",
                    models.CharField(
                        blank=True,
                        default="noreply@g.ucmerced.edu",
                        help_text="Sender email address for both SES and SMTP.",
                        max_length=254,
                        verbose_name="From Email",
                    ),
                ),
                (
                    "ses_from_name",
                    models.CharField(
                        blank=True,
                        default="Innovate to Grow",
                        max_length=128,
                        verbose_name="From Name",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True,
                        default="smtp.gmail.com",
                        max_length=254,
                        verbose_name="SMTP Host",
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(default=587, verbose_name="SMTP Port"),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(default=True, verbose_name="SMTP Use TLS"),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="SMTP Username",
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="SMTP Password",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Service Config",
                "verbose_name_plural": "Email Service Configs",
            },
        ),
        migrations.CreateModel(
            name="GoogleCredentialConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default",
                        help_text="A label to identify this configuration (e.g. 'Production Sheets', 'Dev Service Account').",
                        max_length=128,
                        verbose_name="Config Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one config can be active. Activating this will deactivate others.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "credentials_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Paste the full contents of the Google service-account JSON key file.",
                        validators=[
                            core.models.base.service_credentials.validate_google_credentials_json
                        ],
                        verbose_name="Service Account JSON",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Google Credential Config",
                "verbose_name_plural": "Google Credential Configs",
            },
        ),
        migrations.CreateModel(
            name="SiteMaintenanceControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_maintenance",
                    models.BooleanField(
                        default=False,
                        help_text="Enable to put the site into maintenance mode.",
                        verbose_name="Maintenance Mode",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="We are performing scheduled maintenance. Please try again shortly.",
                        help_text="Message displayed to users during maintenance.",
                        verbose_name="Maintenance Message",
                    ),
                ),
                (
                    "bypass_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Password that allows authorized users to bypass maintenance mode. Leave blank to disable bypass.",
                        max_length=128,
                        verbose_name="Bypass Password",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Maintenance Control",
                "verbose_name_plural": "Site Maintenance Control",
            },
        ),
        migrations.CreateModel(
            name="SMSServiceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default",
                        help_text="A label to identify this configuration.",
                        max_length=128,
                        verbose_name="Config Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one config can be active. Activating this will deactivate others.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "account_sid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Twilio Account SID (starts with AC).",
                        max_length=64,
                        verbose_name="Account SID",
                    ),
                ),
                (
                    "auth_token",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Auth Token"
                    ),
                ),
                (
                    "verify_sid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Twilio Verify Service SID (starts with VA).",
                        max_length=64,
                        verbose_name="Verify Service SID",
                    ),
                ),
                (
                    "from_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Twilio phone number for sending messages (e.g. +1234567890). Used for test SMS.",
                        max_length=20,
                        verbose_name="From Phone Number",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SMS Service Config",
                "verbose_name_plural": "SMS Service Configs",
            },
        ),
    ]
