# Generated by Django 5.2.10 on 2026-04-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_gmailimportconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailserviceconfig",
            name="ses_max_send_rate",
            field=models.PositiveIntegerField(
                default=14,
                help_text="Maximum emails per second via SES. Check your SES account quota. Default 14 for sandbox.",
                verbose_name="SES Max Send Rate",
            ),
        ),
    ]
