# Generated by Django 5.2.10 on 2026-04-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_emailserviceconfig_ses_max_send_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailserviceconfig",
            name="ses_max_send_rate",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Max emails per second for bulk campaigns. Keep below SES account limit to leave room for transactional mail.",
                verbose_name="Campaign Send Rate (emails/sec)",
            ),
        ),
    ]
