# Generated by Django 5.2.10 on 2026-04-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_emailserviceconfig_ses_max_send_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSCredentialConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default",
                        help_text="A label to identify this configuration (e.g. 'Production IAM', 'Dev Account').",
                        max_length=128,
                        verbose_name="Config Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one config can be active. Activating this will deactivate others.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "access_key_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AWS IAM access key ID (starts with AKIA…).",
                        max_length=128,
                        verbose_name="Access Key ID",
                    ),
                ),
                (
                    "secret_access_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Secret Access Key",
                    ),
                ),
                (
                    "default_region",
                    models.CharField(
                        blank=True,
                        default="us-west-2",
                        help_text="AWS region used when a service does not specify its own.",
                        max_length=32,
                        verbose_name="Default Region",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AWS Credential Config",
                "verbose_name_plural": "AWS Credential Configs",
            },
        ),
    ]
