# Generated by Django 5.2.10 on 2026-04-12 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_awscredentialconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemIntelligenceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default",
                        help_text="A label to identify this configuration.",
                        max_length=128,
                        verbose_name="Config Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one config can be active. Activating this will deactivate others.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        default="anthropic.claude-3-5-sonnet-20241022-v2:0",
                        help_text="Amazon Bedrock model identifier (e.g. anthropic.claude-3-5-sonnet-20241022-v2:0).",
                        max_length=256,
                        verbose_name="Bedrock Model ID",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        default="You are a helpful AI assistant for the Innovate to Grow admin team.",
                        verbose_name="System Prompt",
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=4096,
                        help_text="Maximum number of tokens in the model response.",
                        verbose_name="Max Tokens",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Sampling temperature (0.0 = deterministic, 1.0 = creative).",
                        verbose_name="Temperature",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Intelligence Config",
                "verbose_name_plural": "System Intelligence Configs",
            },
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="New Chat", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "model_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The Bedrock model that produced this response (for audit).",
                        max_length=256,
                        verbose_name="Model ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.chatconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "ordering": ["created_at"],
            },
        ),
    ]
