# Generated by Django 5.2.10 on 2026-04-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_system_intelligence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemintelligenceconfig",
            name="model_id",
            field=models.CharField(
                default="anthropic.claude-sonnet-4-20250514-v1:0",
                help_text="Amazon Bedrock model identifier (e.g. anthropic.claude-sonnet-4-20250514-v1:0).",
                max_length=256,
                verbose_name="Bedrock Model ID",
            ),
        ),
    ]
