# Generated by Django 5.2.10 on 2026-04-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_update_default_model_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemintelligenceconfig",
            name="model_id",
            field=models.CharField(
                choices=[
                    (
                        "Anthropic Claude",
                        [
                            (
                                "anthropic.claude-sonnet-4-20250514-v1:0",
                                "Claude Sonnet 4",
                            ),
                            (
                                "anthropic.claude-sonnet-4-5-20250929-v1:0",
                                "Claude Sonnet 4.5",
                            ),
                            ("anthropic.claude-sonnet-4-6", "Claude Sonnet 4.6"),
                            ("anthropic.claude-opus-4-6-v1", "Claude Opus 4.6"),
                        ],
                    ),
                    (
                        "Amazon Titan",
                        [
                            ("amazon.titan-text-premier-v1:0", "Titan Text Premier"),
                            ("amazon.titan-text-express-v1", "Titan Text Express"),
                            ("amazon.titan-text-lite-v1", "Titan Text Lite"),
                        ],
                    ),
                    (
                        "Meta Llama",
                        [
                            (
                                "meta.llama3-1-70b-instruct-v1:0",
                                "Llama 3.1 70B Instruct",
                            ),
                            ("meta.llama3-1-8b-instruct-v1:0", "Llama 3.1 8B Instruct"),
                        ],
                    ),
                    (
                        "Mistral",
                        [
                            ("mistral.mistral-large-2407-v1:0", "Mistral Large"),
                            (
                                "mistral.mixtral-8x7b-instruct-v0:1",
                                "Mixtral 8x7B Instruct",
                            ),
                        ],
                    ),
                ],
                default="anthropic.claude-sonnet-4-20250514-v1:0",
                help_text="Select an Amazon Bedrock model for AI chat.",
                max_length=256,
                verbose_name="Bedrock Model",
            ),
        ),
    ]
