# Generated by Django 5.2.10 on 2026-04-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_bedrock_inference_profile_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemintelligenceconfig",
            name="model_id",
            field=models.CharField(
                default="us.anthropic.claude-sonnet-4-20250514-v1:0",
                help_text="Model or inference profile ID to use for AI chat.",
                max_length=256,
                verbose_name="Bedrock Model",
            ),
        ),
        migrations.AlterField(
            model_name="systemintelligenceconfig",
            name="system_prompt",
            field=models.TextField(
                blank=True,
                default="You are a helpful AI assistant for the Innovate to Grow admin team. You have access to the application database and can query members, events, registrations, projects, email campaigns, CMS pages, news articles, and analytics data. Use the available tools to look up data when answering questions. Always verify facts by querying the database rather than guessing.",
                verbose_name="System Prompt",
            ),
        ),
    ]
