# Generated by Django 5.2.10 on 2026-04-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_hardcoded_model_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="awscredentialconfig",
            name="default_model_id",
            field=models.CharField(
                blank=True,
                default="us.anthropic.claude-sonnet-4-20250514-v1:0",
                help_text="Site-wide default Bedrock model or inference profile ID.",
                max_length=256,
                verbose_name="Default AI Model",
            ),
        ),
    ]
