# Generated by Django 5.2.10 on 2026-04-16 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_awscredentialconfig_default_model_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemintelligenceconfig",
            name="model_id",
        ),
    ]
