# Generated by Django 5.2.10 on 2026-04-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_systemintelligenceconfig_model_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="tool_calls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Bedrock tool invocations for this assistant turn (name, input, result preview).",
            ),
        ),
    ]
