# Generated by Django 5.2.10 on 2026-04-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_chatmessage_tool_calls"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="token_usage",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Token consumption for this turn (inputTokens, outputTokens, totalTokens).",
            ),
        ),
    ]
