# Generated by Codex on 2026-04-25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_chatmessage_token_usage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemIntelligenceActionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("cms_page_update", "CMS page update"),
                            ("db_create", "Database create"),
                            ("db_update", "Database update"),
                            ("db_delete", "Database delete"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("target_app_label", models.CharField(blank=True, default="", max_length=100)),
                ("target_model", models.CharField(blank=True, default="", max_length=100)),
                ("target_pk", models.CharField(blank=True, default="", max_length=128)),
                ("target_repr", models.CharField(blank=True, default="", max_length=300)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("before_snapshot", models.JSONField(blank=True, default=dict)),
                ("after_snapshot", models.JSONField(blank=True, default=dict)),
                ("diff", models.JSONField(blank=True, default=list)),
                ("preview_token", models.CharField(blank=True, default="", max_length=64)),
                ("preview_url", models.URLField(blank=True, default="", max_length=1000)),
                ("preview_expires_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assistant_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_requests",
                        to="core.chatmessage",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_requests",
                        to="core.chatconversation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_intelligence_action_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_system_intelligence_action_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Intelligence Action Request",
                "verbose_name_plural": "System Intelligence Action Requests",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="systemintelligenceactionrequest",
            index=models.Index(fields=["conversation", "created_at"], name="core_system_convers_3dc035_idx"),
        ),
        migrations.AddIndex(
            model_name="systemintelligenceactionrequest",
            index=models.Index(fields=["status", "created_at"], name="core_system_status_00932e_idx"),
        ),
    ]
