# Generated by Codex on 2026-04-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_systemintelligenceactionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="context_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Rolling summary of older System Intelligence conversation context.",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="context_summary_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="context_summary_through_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Newest message included in the rolling context summary.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="context_usage",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Estimated context prepared for this turn before invoking the model.",
            ),
        ),
    ]
