# Generated by Django 5.2.10 on 2026-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_system_intelligence_context_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="mode",
            field=models.CharField(
                choices=[("normal", "Normal"), ("plan", "Plan-only")],
                default="normal",
                help_text="Plan mode disables write tools and steers the agent toward planning only.",
                max_length=16,
            ),
        ),
    ]
