# Generated by Django 5.2.10 on 2026-04-27 09:28

import core.models.base.system_intelligence.export
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_chatconversation_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemIntelligenceExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Export", max_length=200)),
                ("filename", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.base.system_intelligence.export._export_upload_to
                    ),
                ),
                (
                    "model_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("field_names", models.JSONField(blank=True, default=list)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="core.chatconversation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_intelligence_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Intelligence Export",
                "ordering": ["-created_at"],
            },
        ),
    ]
