# Generated by Django 5.2.10 on 2026-04-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_system_intelligence_project_control_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="auto_title",
            field=models.BooleanField(
                default=True,
                help_text="True until the title has been explicitly set, either by the user or by the first-turn auto-rename.",
            ),
        ),
    ]
