# Generated by Django 5.2.10 on 2026-05-16 21:01

from django.db import migrations


REMOVED_SYSTEM_INTELLIGENCE_MODELS = [
    "chatconversation",
    "chatmessage",
    "systemintelligenceactionrequest",
    "systemintelligenceconfig",
    "systemintelligenceexport",
]


def delete_core_system_intelligence_contenttypes(apps, schema_editor):
    content_type = apps.get_model("contenttypes", "ContentType")
    content_type.objects.filter(app_label="core", model__in=REMOVED_SYSTEM_INTELLIGENCE_MODELS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0020_chatconversation_auto_title"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="systemintelligenceactionrequest",
            name="core_system_convers_3dc035_idx",
        ),
        migrations.RemoveIndex(
            model_name="systemintelligenceactionrequest",
            name="core_system_status_00932e_idx",
        ),
        migrations.RemoveField(
            model_name="chatconversation",
            name="context_summary_through_message",
        ),
        migrations.RemoveField(
            model_name="chatconversation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="systemintelligenceactionrequest",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="systemintelligenceexport",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="systemintelligenceactionrequest",
            name="assistant_message",
        ),
        migrations.RemoveField(
            model_name="systemintelligenceactionrequest",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="systemintelligenceactionrequest",
            name="reviewed_by",
        ),
        migrations.DeleteModel(
            name="SystemIntelligenceConfig",
        ),
        migrations.RemoveField(
            model_name="systemintelligenceexport",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="ChatConversation",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="SystemIntelligenceActionRequest",
        ),
        migrations.DeleteModel(
            name="SystemIntelligenceExport",
        ),
        migrations.RunPython(delete_core_system_intelligence_contenttypes, migrations.RunPython.noop),
    ]
