# Generated by Cursor on 2026-05-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system_intelligence", "0002_config_default_model_id"),
        ("core", "0021_remove_chatconversation_context_summary_through_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awscredentialconfig",
            name="default_model_id",
        ),
    ]
