# Generated by Django 5.2 for SES-only notification delivery.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_rename_gmail_import_config_to_access_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailserviceconfig",
            name="smtp_host",
        ),
        migrations.RemoveField(
            model_name="emailserviceconfig",
            name="smtp_password",
        ),
        migrations.RemoveField(
            model_name="emailserviceconfig",
            name="smtp_port",
        ),
        migrations.RemoveField(
            model_name="emailserviceconfig",
            name="smtp_use_tls",
        ),
        migrations.RemoveField(
            model_name="emailserviceconfig",
            name="smtp_username",
        ),
        migrations.AlterField(
            model_name="emailserviceconfig",
            name="name",
            field=models.CharField(
                default="Default",
                help_text="A label to identify this configuration (e.g. 'Production SES', 'Dev SES').",
                max_length=128,
                verbose_name="Config Name",
            ),
        ),
        migrations.AlterField(
            model_name="emailserviceconfig",
            name="ses_from_email",
            field=models.CharField(
                blank=True,
                default="noreply@g.ucmerced.edu",
                help_text="Sender email address used by AWS SES.",
                max_length=254,
                verbose_name="From Email",
            ),
        ),
    ]
